name: nxviz
channels:
- ericmjl
- defaults
- conda-forge
dependencies:
- matplotlib
- networkx
- numpy
- pip
- python=3.5
- setuptools
- pytest
- pycodestyle
- pip:
  - coverage
  - click
  - hypothesis
  - polcart
