name: nxviz
channels:
- conda-forge
- defaults
- ericmjl
dependencies:
- python=3.6
- matplotlib
- networkx=2.0
- numpy
- pip
- setuptools
- pycodestyle
- pydocstyle
- click
- pandas
- coverage
- pytest-cov
- sphinx
- cython
- palettable
- hypothesis
- pytest
- cryptography
- pyyaml
- twine
- pip:
    - sphinxcontrib-fulltoc
    - pipreqs
