name: nxviz
channels:
- conda-forge
- defaults
- ericmjl
dependencies:
- python>=3.5
- matplotlib>=2.0.0
- networkx>=1.11
- numpy>=1.13.1
- pip
- setuptools
- pycodestyle
- click
- pandas>=0.20.0
- coverage
- pytest-cov
- sphinx
- cython
- palettable=3.0.0
- hypothesis=3.6.1
- pytest=3.2.1
- polcart=2017.1.16.14.45
- pip:
    - sphinxcontrib-fulltoc==1.2.0
    - cryptography==2.0.3
