name: nxviz
channels:
- conda-forge
- defaults
- ericmjl
dependencies:
- matplotlib
- networkx
- numpy
- pip
- python=3.5
- setuptools
- pytest
- pycodestyle
- hypothesis
- click
- polcart
- pip:
  - coverage
