name: nxviz
channels:
- conda-forge
- defaults
- ericmjl
dependencies:
- matplotlib=2.0.2
- networkx=1.11
- numpy=1.13.1
- pip
- python=3.5
- setuptools
- pycodestyle
- click
- pandas=0.20.3
- coverage
- sphinx
- cython
- pip:
    - sphinxcontrib-fulltoc==1.2.0
    - cryptography==2.0.3
    - hypothesis==3.6.1
    - pytest==3.0.6
    - polcart==2017.1.16.14.45
    - palettable==3.2.1
